name: Build TWA APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        # هذا الأمر سيقوم بإنشاء الإعدادات والبناء في خطوة واحدة
        run: |
          bubblewrap init --manifest=https://my-ai-app-kappa-khaki.vercel.app/manifest.json --extracp=false
          bubblewrap build --skipConfig
          
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Visual-AI-App
          path: ./*.apk
