name: Build TWA APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        # استخدمنا هنا "yes" لإجابة كل الأسئلة بـ نعم تلقائياً
        run: |
          yes | bubblewrap init --manifest=https://my-ai-app-kappa-khaki.vercel.app/manifest.json --extracp=false
          bubblewrap build --skipConfig
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Visual-AI-App
          path: ./*.apk
